(function(c){c.ArmContext={_lastUnicalNumber:0,GetNewUnicalNumber:function(){return this._lastUnicalNumber+=1}}})(window);
(function(){ArmContext.InternalRepresentation=function(c){var b={};b._primitive=c;b._points=new $M([[0,0,1]]);b.GetPoints=function(){return this._points.elements};b.ShowPoints=function(a){var d=this.GetPoints();a.save();a.beginPath();for(var b in d)a.moveTo(d[b][0],d[b][1]),a.arc(d[b][0],d[b][1],3,0,2*Math.PI,!1);a.closePath();CTX.fillStyle="#ff0000";a.stroke();a.fill();a.restore();return this};b.ShowDebugInfo=function(){var a=this.GetPoints();console.log("Points of internal representation");for(var d in a)console.log(a[d])};
b.SetLisener=function(a,d){gizmo.Filter(a,"String");gizmo.Filter(d,"Function");a&&d&&(this["_"+a]=d);return this};b.GetLisener=function(a){gizmo.Filter(a,"String");return this["_"+a]?this["_"+a]:!1};return b}})();
(function(){ArmContext.GlobalRepresentation=function(c){var b={};b._primitive=c;b._points=new $M([[0,0,1]]);b._polygone=new gizmo.Math.Polygone(b._points.elements);b.GetPoints=function(){return this._points.elements};b.SetPoints=function(a){gizmo.Filter(a,"Array");this._points.elements=a};b.GetMatrixOfPoints=function(){return this._points};b.SetMatrixOfPoints=function(a){gizmo.Filter(a,"Object");return this._points=a};b.Update=function(a,d,b){gizmo.Filter(a,"Object");gizmo.Filter(d,"Object");gizmo.Filter(b,
"Object");this.SetPoints(a.GetPoints());this.SetMatrixOfPoints(this.GetMatrixOfPoints().x(b.GetMatrix()));this.UpdatePolygone();return this};b.UpdatePolygone=function(){arrVectors=[];var a=this.GetPoints(),d;for(d in a)arrVectors.push(new gizmo.Math.Vector2D(a[d][0],a[d][1]));this._polygone=new gizmo.Math.Polygone(arrVectors);return this};b.HasPoint=function(a,d){gizmo.Filter(a,"Number");gizmo.Filter(d,"Number");return this._polygone.HasPoint({x:a,y:d})};b.ShowDebugInfo=function(){var a=this.GetPoints();
console.log("Points of global representation");for(var d in a)console.log(a[d])};b.ShowPoints=function(){var a=this.GetPoints(),d;for(d in a)CTX.save(),CTX.beginPath(),CTX.fillStyle="#00ff00",CTX.rect(a[d][0]-2,a[d][1]-2,4,4),CTX.stroke(),CTX.fill(),CTX.closePath(),CTX.restore()};return b}})();
(function(){ArmContext.C2dContextRepresentation=function(c){var b={};b._primitive=c;b._ctx=null;b._layer=null;b._globalAlpha="default";b._shadowColor="default";b._shadowBlur="default";b._shadowOffsetX="default";b._shadowOffsetY="default";b._zindex=0;b._boundingBox={};b._pictureUnderPrimitive={};b.Set=function(a){for(var d in a)switch(d){case "ctx":this.SetCtx(a[d]);break;case "layer":this.SetLayer(a[d]);this.SetCtx(this.GetLayer().GetCtx());break;case "globalAlpha":this.SetGlobalAlpha(a[d]);break;
case "shadowColor":this.SetShadowColor(a[d]);break;case "shadowBlur":this.SetBlur(a[d]);break;case "shadowOffsetX":this.SetShadowOffsetX(a[d]);break;case "shadowOffsetY":this.SetShadowOffsetY(a[d]);break;case "zindex":this.SetZindex(a[d])}};b.SetCtx=function(a){gizmo.Filter(a,"CanvasRenderingContext2D");this._ctx=a};b.SetLayer=function(a){gizmo.Filter(a,"Object");this._layer=a;this._layer.AddPrimitive(this._primitive)};b.SetGlobalAlpha=function(a){gizmo.Filter(a,"Number");this._globalAlpha=a};b.SetShadowColor=
function(a){gizmo.Filter(a,"String");this._shadowColor=a};b.SetShadowBlur=function(a){gizmo.Filter(a,"Number");this._shadowBlur=a};b.SetShadowOffsetX=function(a){gizmo.Filter(a,"Number");this._shadowOffsetX=a};b.SetShadowOffsetY=function(a){gizmo.Filter(a,"Number");this._shadowOffsetY=a};b.SetZindex=function(a){gizmo.Filter(a,"Number");this._zindex=a;this.GetLayer().SortByZindex()};b.GetCtx=function(){return this._ctx};b.GetLayer=function(){return this._layer};b.GetGlobalAlpha=function(){return this._globalAlpha};
b.GetShadowColor=function(){return this._shadowColor};b.GetShadowBlur=function(){return this._shadowBlur};b.GetShadowOffsetX=function(){return this._shadowOffsetX};b.GetShadowOffsetY=function(){return this._shadowOffsetY};b.GetZindex=function(){return this._zindex};b.SetLisener=function(a,d){gizmo.Filter(a,"String");gizmo.Filter(d,"Function");a&&d&&(this["_"+a]=d);return this};b.GetLisener=function(a){gizmo.Filter(a,"String");return this["_"+a]?this["_"+a]:!1};b.ShowDebugInfo=function(){console.log("VisualProperties:");
console.log("Method have not realisation")};return b}})();
(function(){ArmContext.MvMatrix=function(c){var b={};b._primitive=c;b._matrix=new $M([[1,0,0],[0,1,0],[0,0,1]]);b.Rotate=function(a){var d=Math.cos(a),a=Math.sin(a),d=new $M([[d,a,0],[-a,d,0],[0,0,1]]);this._matrix=this._matrix.x(d);this._onChanged&&this._onChanged.call(c);this._onChanged&&this._onChanged.call(c);return this};b.Scale=function(a,d){gizmo.Filter(a,"Number");gizmo.Filter(d,"Number");var b=new $M([[a,0,0],[0,d,0],[0,0,1]]);this._matrix=this._matrix.x(b);this._onChanged&&this._onChanged.call(c);
return this};b.Translate=function(a,d){gizmo.Filter(a,"Number");gizmo.Filter(d,"Number");var b=new $M([[1,0,0],[0,1,0],[a,d,1]]);this._matrix=this._matrix.x(b);this._onChanged&&this._onChanged.call(c);return this};b.Scos=function(a,d){gizmo.Filter(a,"Number");gizmo.Filter(d,"Number");var b=new $M([[1,d,0],[a,1,0],[0,0,1]]);this._matrix=this._matrix.x(b);this._onChanged&&this._onChanged.call(c);return this};b.GetMatrix=function(){return this._matrix};b.GetTransformParams=function(){var a=this.GetMatrix();
return{a:a.elements[0][0],b:a.elements[0][1],c:a.elements[1][0],d:a.elements[1][1],e:a.elements[2][0],f:a.elements[2][1]}};b.SetLisener=function(a,d){gizmo.Filter(a,"String");gizmo.Filter(d,"Function");a&&d&&(this["_"+a]=d);return this};b.GetLisener=function(a){gizmo.Filter(a,"String");return this["_"+a]?this["_"+a]:!1};b.ShowDebugInfo=function(){var a=this.GetMatrix();console.log("mvMatrix:");console.log(a.elements[0]);console.log(a.elements[1]);console.log(a.elements[2])};return b}})();
(function(){ArmContext.Debug=function(c){gizmo.Filter(c,"Object");var b={};b.object=c;b.ShowDebugInfo=function(){console.log("<<Primitive>> DebugInfo");this.object._2dContextRepresentation.ShowDebugInfo();this.object._interalRepresentation.ShowDebugInfo();this.object._globalRepresentation.ShowDebugInfo();this.object._mvMatrix.ShowDebugInfo()};return b}})();
(function(c){c.ArmContext.BoundingBox=function(b){var a={};a._rect=[{point0:new gizmo.Math.Point2D(0,0),point1:new gizmo.Math.Point2D(0,0),point2:new gizmo.Math.Point2D(0,0),point3:new gizmo.Math.Point2D(0,0),width:0,height:0},{point0:new gizmo.Math.Point2D(0,0),point1:new gizmo.Math.Point2D(0,0),point2:new gizmo.Math.Point2D(0,0),point3:new gizmo.Math.Point2D(0,0),width:0,height:0}];a.GetNewPoints=function(){return this._rect[0]};a.GetOldPoints=function(){return this._rect[1]};a.IntersectWith=function(a){var b=
this.GetOldPoints(),a=a.GetOldPoints();return a.point0.x>b.point1.x||a.point1.x<b.point0.x||a.point0.y>b.point3.y||a.point3.y<b.point0.x?!1:!0};a.SumWith=function(a){var b=this.GetOldPoints(),a=a.GetOldPoints(),c=b.point0.x,e=b.point0.y,f=b.point2.x,g=b.point2.y,c=Math.min(b.point0.x,b.point1.x,b.point2.x,b.point3.x,a.point0.x,a.point1.x,a.point2.x,a.point3.x),e=Math.min(b.point0.y,b.point1.y,b.point2.y,b.point3.y,a.point0.y,a.point1.y,a.point2.y,a.point3.y),f=Math.max(b.point0.x,b.point1.x,b.point2.x,
b.point3.x,a.point0.x,a.point1.x,a.point2.x,a.point3.x),g=Math.max(b.point0.y,b.point1.y,b.point2.y,b.point3.y,a.point0.y,a.point1.y,a.point2.y,a.point3.y);return new ArmContext.BoundingBox({points:{point0:{x:c,y:e},point1:{x:f,y:g}}})};a.Update=function(a){var a=a.GetPoints(),b=a[0][0],c=a[0][1],e=a[0][0],f=a[0][1],g;for(g in a)var h=a[g],b=Math.min(h[0],b),c=Math.min(h[1],c),e=Math.max(h[0],e),f=Math.max(h[1],f);g={point0:{x:b,y:c},point1:{x:e,y:c},point2:{x:e,y:f},point3:{x:b,y:f},width:e-b,height:f-
c};this._rect.reverse();this._rect[0]=g};a.Set=function(a){for(var b in a)switch(b){case "points":var c=a[b];gizmo.Filter(c,"Object");gizmo.Filter(c.point0,"Object");gizmo.Filter(c.point1,"Object");c={point0:c.point0,point1:c.point1,point2:{x:c.point1.x,y:c.point0.y},point3:{x:c.point0.x,y:c.point1.y},width:c.point1.x-c.point0.x,height:c.point1.y-c.point0.y};this._rect[0]=c;this._rect[1]=c}};a.Set(b||{});return a}})(window);
(function(c){c.ArmContext.TransformQuene=function(){return{Push:function(b){try{return this._stack.push(b),!0}catch(a){return!1}},Pop:function(){var b=this._stack.shift();return void 0!=b?b:!1},ProcessEvents:function(b){for(var a;a=this.Pop();)switch(a.name){case "Translate":b._translate(a.e);break;case "Rotate":b._rotate(a.e);break;case "Scale":b._scale(a.e);break;case "Scos":b._scos(a)}},_stack:[]}}})(window);
(function(c){c.ArmContext.Primitive=function(){var b={_internalRepresentation:null,_2dContextRepresentation:null,_globalRepresentation:null};b._mvMatrix=ArmContext.MvMatrix(b);b._debug=ArmContext.Debug(b);b._boundingBox=ArmContext.BoundingBox();b._transformQuene=ArmContext.TransformQuene();b._isLisened=!0;b._isChanged=!0;b.TranslateTo=function(a){gizmo.Filter(a,"Object");gizmo.Filter(a.x,"Number");gizmo.Filter(a.y,"Number");var b=this._globalRepresentation.GetX(),c=this._globalRepresentation.GetY();
this._transformQuene.Push({name:"Translate",e:{x:a.x-b,y:a.y-c}});return this};b.Translate=function(a){gizmo.Filter(a,"Object");gizmo.Filter(a.x,"Number");gizmo.Filter(a.y,"Number");this._transformQuene.Push({name:"Translate",e:a});return this};b._translate=function(a){gizmo.Filter(a,"Object");gizmo.Filter(a.x,"Number");gizmo.Filter(a.y,"Number");this._mvMatrix.Translate(a.x,a.y);return this};b.Rotate=function(a){gizmo.Filter(a.gradAngle||a.radAngle,"Number");gizmo.Filter(a.x,"Number");gizmo.Filter(a.y,
"Number");var b=a.radAngle||(360<a.gradAngle?a.gradAngle%360:a.gradAngle)/180*Math.PI;this._transformQuene.Push({name:"Translate",e:{x:-a.x,y:-a.y}});this._transformQuene.Push({name:"Rotate",e:{radAngle:b}});this._transformQuene.Push({name:"Translate",e:{x:a.x,y:a.y}});return this};b._rotate=function(a){gizmo.Filter(a.radAngle,"Number");this._mvMatrix.Rotate(a.radAngle);return this};b.Scale=function(a){gizmo.Filter(a,"Object");gizmo.Filter(a.x,"Number");gizmo.Filter(a.y,"Number");var b=this._globalRepresentation.GetX(),
c=this._globalRepresentation.GetY(),b=b-b*a.x,c=c-c*a.y;this._transformQuene.Push({name:"Scale",e:{x:a.x,y:a.y}});this._transformQuene.Push({name:"Translate",e:{x:b,y:c}});return this};b._scale=function(a){gizmo.Filter(a,"Object");gizmo.Filter(a.x,"Number");gizmo.Filter(a.y,"Number");this._mvMatrix.Scale(a.x,a.y)};b.Scos=function(a){gizmo.Filter(a,"Object");gizmo.Filter(a.x,"Number");gizmo.Filter(a.y,"Number");this._transformQuene.Push({name:"Scos",e:{x:a.x,y:a.y}});return this};b._scos=function(a){gizmo.Filter(a,
"Object");gizmo.Filter(a.x,"Number");gizmo.Filter(a.y,"Number");this._mvMatrix.Scos(a.x,a.y)};b.Draw=function(){console.log("Virtual method Draw");return this};b.Clear=function(){console.log("Virtual method Clear");return this};b.HasPoint=function(a){gizmo.Filter(a,"Object");gizmo.Filter(a.x,"Number");gizmo.Filter(a.y,"Number");return this._globalRepresentation.HasPoint(a.x,a.y)};b.GetBoundingBox=function(){return this._boundingBox};b.BoundingBoxHaveIntersectionWith=function(a){return this._boundingBox.IntersectWith(a.GetBoundingBox())};
b.Update=function(){this.SetUnchanged();this._transformQuene.ProcessEvents(this);this._globalRepresentation.Update(this._internalRepresentation,this._2dContextRepresentation,this._mvMatrix);this._boundingBox.Update(this._globalRepresentation)};b.Set=function(a){this._internalRepresentation.Set(a);this._2dContextRepresentation.Set(a)};b.SetLisened=function(a){gizmo.Filter(a,"Boolean");this._isLisened=a};b.IsLisened=function(){return this._isLisened};b.SetChanged=function(){this._isChanged=!0};b.SetUnchanged=
function(){this._isChanged=!1};b.IsChanged=function(){return this._isChanged};return b}})(window);(function(){ArmContext.Image2dContextRepresentation=function(c){c=ArmContext.C2dContextRepresentation(c);c.parentSet=c.Set?c.Set:null;c._image=null;c.GetImage=function(){return this._image};c.Set=function(b){this.parentSet&&this.parentSet(b);this._image=b.image||this._image};return c}})();
(function(){ArmContext.ImageGlobalRepresentation=function(){var c=ArmContext.GlobalRepresentation();c.GetX=function(){return this.GetPoints()[0][0]};c.GetY=function(){return this.GetPoints()[0][1]};c.GetWidth=function(){this.GetPoints();return points[2][0]-points[0][0]};c.GetHeight=function(){this.GetPoints();return points[2][1]-points[0][1]};c.ShowPoints=function(){var b=this.GetPoints();CTX.save();CTX.beginPath();CTX.fillStyle="#ff0000";CTX.rect(b[0][0]-2,b[0][1]-2,4,4);CTX.stroke();CTX.fill();
CTX.closePath();CTX.restore();CTX.save();CTX.beginPath();CTX.fillStyle="#00ff00";CTX.rect(b[1][0]-2,b[1][1]-2,4,4);CTX.stroke();CTX.fill();CTX.closePath();CTX.restore();CTX.save();CTX.beginPath();CTX.fillStyle="#0000ff";CTX.rect(b[2][0]-2,b[2][1]-2,4,4);CTX.stroke();CTX.fill();CTX.closePath();CTX.restore();CTX.save();CTX.beginPath();CTX.fillStyle="#aaffbb";CTX.rect(b[3][0]-2,b[3][1]-2,4,4);CTX.stroke();CTX.fill();CTX.closePath();CTX.restore()};return c}})();
(function(){ArmContext.ImageInternalRepresentation=function(c){c=new ArmContext.InternalRepresentation(c);this._height=this._width=10;c.GetWidth=function(){return this._width};c.SetWidth=function(b){gizmo.Filter(b,"Number");this.Update({width:b,height:this.GetHeight()})};c.GetHeight=function(){return this._height};c.SetHeight=function(b){gizmo.Filter(b,"Number");this.UpdatePoints({x:this.GetX(),y:this.GetY(),width:this.GetWidth(),height:b})};c.GetPointsOfMatrix=function(){return this._points};c.SetPointsOfMatrix=
function(b){gizmo.Filter(b,"Array");return this._points};c.Set=function(b){this._width=b.width||this._width;this._height=b.height||this._height;this._points=new $M([[0,0,1],[this._width,0,1],[this._width,this._height,1],[0,this._height,1]])};return c}})();
(function(c){c.ArmContext.Image=function(b){gizmo.Filter(b,"Object");var a=ArmContext.Primitive();a._internalRepresentation=ArmContext.ImageInternalRepresentation();a._2dContextRepresentation=ArmContext.Image2dContextRepresentation(a);a._globalRepresentation=ArmContext.ImageGlobalRepresentation();a.Draw=function(){var a=this._2dContextRepresentation,b=this._internalRepresentation,c=a._ctx;c.save();params=this._mvMatrix.GetTransformParams();c.setTransform(params.a,params.b,params.c,params.d,params.e,
params.f);c.drawImage(a.GetImage(),0,0,b.GetWidth(),b.GetHeight());c.restore()};a.Clear=function(){var a=this._2dContextRepresentation,b=this._boundingBox.GetOldPoints();a.GetCtx().clearRect(b.point0.x,b.point0.y,b.width,b.height)};a._internalRepresentation.SetLisener("onChanged",function(){this.SetChanged()});a._2dContextRepresentation.SetLisener("onChanged",function(){this.SetChanged()});a._mvMatrix.SetLisener("onChanged",function(){this.SetChanged()});a.Set(b);a.Update();return a}})(window);
(function(){ArmContext.Rect2dContextRepresentation=function(c){var b=ArmContext.C2dContextRepresentation(c);b.parentSet=b.Set?b.Set:null;b._fillObject="default";b._strokeObject="default";b._lineWidth="default";b._lineDash="default";b._miterLimit="default";b._lineCap="default";b._lineJoin="default";b.GetFillObject=function(){return this._fillObject};b.GetStrokeObject=function(){return this._strokeObject};b.GetLineWidth=function(){return this._lineWidth};b.GetLineDash=function(){return this._lineDash};
b.GetMiterLimit=function(){return this._miterLimit};b.GetLineCap=function(){return this._lineCap};b.GetLineJoin=function(){return this._lineJoin};b.Set=function(a){this.parentSet&&this.parentSet(a);for(var b in a)switch(b){case "fillObject":this._fillObject=a[b];this._onChanged&&this._onChanged.call(c);break;case "strokeObject":this._strokeObject=a[b];this._onChanged&&this._onChanged.call(c);break;case "lineWidth":this._lineWidth=a[b];this._onChanged&&this._onChanged.call(c);break;case "lineDash":this._lineDash=
a[b];this._onChanged&&this._onChanged.call(c);break;case "miterLimit":this._miterLimit=a[b];this._onChanged&&this._onChanged.call(c);break;case "lineCap":switch(a[b]){case "butt":this._lineCap=a[b];this._onChanged&&this._onChanged.call(c);break;case "round":this._lineCap=a[b];this._onChanged&&this._onChanged.call(c);break;case "square":this._lineCap=a[b],this._onChanged&&this._onChanged.call(c)}this._onChanged&&this._onChanged.call(c);break;case "lineJoin":switch(a[b]){case "miter":this._lineJoin=
a[b];this._onChanged&&this._onChanged.call(c);break;case "round":this._lineJoin=a[b];this._onChanged&&this._onChanged.call(c);break;case "bevel":this._lineJoin=a[b],this._onChanged&&this._onChanged.call(c)}this._onChanged&&this._onChanged.call(c)}};return b}})();
(function(){ArmContext.RectGlobalRepresentation=function(){var c=ArmContext.GlobalRepresentation();c.GetX=function(){return this.GetPoints()[0][0]};c.GetY=function(){return this.GetPoints()[0][1]};c.GetWidth=function(){this.GetPoints();return points[2][0]-points[0][0]};c.GetHeight=function(){this.GetPoints();return points[2][1]-points[0][1]};c.Update=function(b,a,d){gizmo.Filter(b,"Object");gizmo.Filter(a,"Object");gizmo.Filter(d,"Object");a=("default"!=a.GetLineWidth()?a.GetLineWidth():2)/2+0.5;
b=b.GetPoints();this.SetPoints([[b[0][0]-a,b[0][1]-a,b[0][2]],[b[1][0]+a,b[1][1]-a,b[1][2]],[b[2][0]+a,b[2][1]+a,b[2][2]],[b[3][0]-a,b[3][1]+a,b[3][2]]]);this.SetMatrixOfPoints(this.GetMatrixOfPoints().x(d.GetMatrix()));this.UpdatePolygone();return this};c.ShowPoints=function(){var b=this.GetPoints();CTX.save();CTX.beginPath();CTX.fillStyle="#ff0000";CTX.rect(b[0][0]-2,b[0][1]-2,4,4);CTX.stroke();CTX.fill();CTX.closePath();CTX.restore();CTX.save();CTX.beginPath();CTX.fillStyle="#00ff00";CTX.rect(b[1][0]-
2,b[1][1]-2,4,4);CTX.stroke();CTX.fill();CTX.closePath();CTX.restore();CTX.save();CTX.beginPath();CTX.fillStyle="#0000ff";CTX.rect(b[2][0]-2,b[2][1]-2,4,4);CTX.stroke();CTX.fill();CTX.closePath();CTX.restore();CTX.save();CTX.beginPath();CTX.fillStyle="#aaffbb";CTX.rect(b[3][0]-2,b[3][1]-2,4,4);CTX.stroke();CTX.fill();CTX.closePath();CTX.restore()};return c}})();
(function(){ArmContext.RectInternalRepresentation=function(c){var b=new ArmContext.InternalRepresentation(c);this._height=this._width=10;b.GetWidth=function(){return this._width};b.SetWidth=function(a){gizmo.Filter(a,"Number");this.Update({width:a,height:this.GetHeight()})};b.GetHeight=function(){return this._height};b.SetHeight=function(a){gizmo.Filter(a,"Number");this.UpdatePoints({x:this.GetX(),y:this.GetY(),width:this.GetWidth(),height:a})};b.GetPointsOfMatrix=function(){return this._points};
b.SetPointsOfMatrix=function(a){gizmo.Filter(a,"Array");return this._points};b.Set=function(a){for(var b in a)switch(b){case "width":this._width=a[b];this._onChanged&&this._onChanged.call(c);break;case "height":this._height=a[b],this._onChanged&&this._onChanged.call(c)}this._points=new $M([[0,0,1],[this._width,0,1],[this._width,this._height,1],[0,this._height,1]])};return b}})();
(function(c){c.ArmContext.Rect=function(b){gizmo.Filter(b,"Object");var a=ArmContext.Primitive();a._internalRepresentation=ArmContext.RectInternalRepresentation(a);a._2dContextRepresentation=ArmContext.Rect2dContextRepresentation(a);a._globalRepresentation=ArmContext.RectGlobalRepresentation(a);a.Draw=function(){var a=this._2dContextRepresentation,b=this._internalRepresentation,c=a.GetCtx();c.save();c.beginPath();params=this._mvMatrix.GetTransformParams();c.setTransform(params.a,params.b,params.c,
params.d,params.e,params.f);c.rect(0,0,b.GetWidth(),b.GetHeight());c.closePath();"default"!=a.GetFillObject()&&c.setFillColor(a.GetFillObject());"default"!=a.GetStrokeObject()&&c.setStrokeColor(a.GetStrokeObject());"default"!=a.GetLineWidth()&&c.setLineWidth(a.GetLineWidth());"default"!=a.GetGlobalAlpha()&&c.setAlpha(a.GetGlobalAlpha());"default"!=a.GetShadowColor()&&(c.shadowColor=a.GetShadowColor());"default"!=a.GetShadowBlur()&&(c.shadowBlur=a.GetShadowBlur());"default"!=a.GetShadowOffsetX()&&
(c.shadowOffsetX=a.GetShadowOffsetX());"default"!=a.GetShadowOffsetY()&&(c.shadowOffsetY=a.GetShadowOffsetY());"default"!=a.GetLineCap()&&c.setLineCap(a.GetLineCap());"default"!=a.GetLineDash()&&c.setLineDash(a.GetLineDash());"default"!=a.GetLineJoin()&&c.setLineJoin(a.GetLineJoin());c.stroke();c.fill();c.restore()};a.Clear=function(){var a=this._2dContextRepresentation,b=a.GetCtx(),c=this._boundingBox.GetOldPoints(),b=a.GetCtx();b.clearRect(c.point0.x,c.point0.y,c.width,c.height)};a._internalRepresentation.SetLisener("onChanged",
function(){this.SetChanged()});a._2dContextRepresentation.SetLisener("onChanged",function(){this.SetChanged()});a._mvMatrix.SetLisener("onChanged",function(){this.SetChanged()});a.Set(b);a.Update();return a}})(window);
(function(c){c.ArmContext.Primitives=function(b){var a={Add:function(a){gizmo.Filter(a,"Object");this._primitives.push(a);this.SortByZindex();return this},Remove:function(a){gizmo.Filter(a,"Object");var b=0;return-1!=(b=this._primitives.indexOf(a))?(delete this._primitives[b],!0):!1},GetArray:function(){return this._primitives},SortByZindex:function(){this._primitives=gizmo.nativeSort({mas:this._primitives,target:"<",field:"_2dContextRepresentation._zindex"})},SetLisener:function(a,b){gizmo.Filter(a,
"String");gizmo.Filter(b,"Function");a&&b&&(this["_"+a]?(gizmo.Filter(this["_"+a],"Array"),-1==this["_"+a].indexOf(b)?this["_"+a].push(b):console.log("This Function allredy added for event "+a+" of layer "+this.GetName())):(this["_"+a]=[],this.SetLisener(a,b)));return this},GetLisener:function(a){gizmo.Filter(a,"String");return this["_"+a]?this["_"+a]:!1},GetTopestPrimitiveUnderPoint:function(a){gizmo.Filter(a,"Object");gizmo.Filter(a.x,"Number");gizmo.Filter(a.y,"Number");for(var b=this._primitives.length-
1;0<=b;b--)if(this._primitives[b].IsLisened()&&this._primitives[b].HasPoint(a))return this._primitives[b];return null},GetChanged:function(){var a=[],b,c;for(c in this._primitives)b=this._primitives[c],b.IsChanged&&a.push(b);return new ArmContext.Primitives({primitives:a})},GetIntersectionGroups:function(){var a,b,c;for(c in this._primitives){a=this._primitives[c];for(var e in this._primitives)b=this._primitives[e],a.BoundingBoxHaveIntersectionWith(b)}},GetOneBoundingBox:function(){var a,b=new ArmContext.BoundingBox,
c;for(c in this._primitives)a=this._primitives[c],a=a.GetBoundingBox(),b=b.SumWith(a);return b},Set:function(a){for(var b in a)switch(b){case "primitives":var c=a[b];gizmo.Filter(c,"Array");for(var e in c)this.Add(c[e])}},_primitives:[]};a.Set(b||{});return a}})(window);
(function(c){c.ArmContext.Layer=function(b){gizmo.Filter(b,"Object");var a={AddPrimitive:function(a){gizmo.Filter(a,"Object");this._primitives.Add(a)},RemovePrimitive:function(a){gizmo.Filter(a,"Object");return this._primitives.Remove(a)},SortByZindex:function(){this._primitives.SortByZindex()},SetLisener:function(a,b){gizmo.Filter(a,"String");gizmo.Filter(b,"Function");a&&b&&(this["_"+a]?(gizmo.Filter(this["_"+a],"Array"),-1==this["_"+a].indexOf(b)?this["_"+a].push(b):console.log("This Function allredy added for event "+
a+" of layer "+this.GetName())):(this["_"+a]=[],this.SetLisener(a,b)));return this},GetLisener:function(a){gizmo.Filter(a,"String");return this["_"+a]?this["_"+a]:!1},GetTopestPrimitiveUnderPoint:function(a){gizmo.Filter(a,"Object");gizmo.Filter(a.x,"Number");gizmo.Filter(a.y,"Number");return this._primitives.GetTopestPrimitiveUnderPoint(a)},SortByZindex:function(){this._primitives.SortByZindex()},SetCtx:function(a){gizmo.Filter(a,"CanvasRenderingContext2D");this._ctx=a},SetName:function(a){gizmo.Filter(a,
"String");this._name=a},GetCtx:function(){return this._ctx},GetName:function(){return this._name},GetDefaultName:function(){return this._defaultName},GetCanvasElement:function(){return this._canvasElement},SetContainerElement:function(a){this._containerElement=a},SetCanvasElement:function(a){gizmo.Filter(a,"HTMLCanvasElement");this._canvasElement=a},ListenMouseEvents:function(){var a=this;this.GetCanvasElement().onmousedown=function(b){a.__onMouseDown(b)};this.GetCanvasElement().onmouseup=function(b){a.__onMouseUp(b)};
this.GetCanvasElement().onmousemove=function(b){a.__onMouseMove(b)}},NotListenMouseEvents:function(){this.GetCanvasElement().onmousedown=null;this.GetCanvasElement().onmouseup=null;this.GetCanvasElement().onmousemove=null},Init:function(){var a;a=null==this._containerElementName?document.getElementsByTagName("body")[0]:document.getElementById(this._containerElementName);var b=document.createElement("canvas");b.width=this._width;b.height=this._height;b.id=this._canvasElemetName;b.style.position="absolute";
a.appendChild(b);var c=b.getContext("2d");this.SetName(this._canvasElementName);this.SetContainerElement(a);this.SetCanvasElement(b);this.SetCtx(c);stats=new Stats;stats.setMode(0);document.body.appendChild(stats.domElement)},CalculateClearAndDrawQuane:function(){this._clearAreas=this._primitives.GetChanged().GetOneBoundingBox()},__draw:function(){var a=this._primitives.GetArray(),b;for(b in a)a[b].Draw()},__clear:function(){stats.begin();var a=this._primitives.GetArray(),b;for(b in a)a[b].Clear()},
__update:function(){var a=this._primitives.GetArray(),b;for(b in a)a[b].Update();stats.end()},ReDraw:function(){this.__clear();this.__draw();this.__update()},__onMouseDown:function(a){if(this._onMouseDown){gizmo.Filter(this._onMouseDown,"Array");for(var b in this._onMouseDown)this._onMouseDown[b](a)}},__onMouseUp:function(a){if(this._onMouseUp){gizmo.Filter(this._onMouseUp,"Array");for(var b in this._onMouseUp)this._onMouseUp[b](a)}},__onMouseMove:function(a){if(this._onMouseMove){gizmo.Filter(this._onMouseMove,
"Array");for(var b in this._onMouseMove)this._onMouseMove[b](a)}},Set:function(b){this.SetName(b.name||this.GetName());a._canvasElementName=null==document.getElementById(this.GetName())?this.GetName():this.GetName()+"."+ArmContext.GetNewUnicalNumber();this._containerElementName=b.container||this._containerElementName;this._width=b.width||this._width;this._height=b.height||this._height;this._left=b.left||this._left;this._top=b.top||this._top;this._zindex=b.zindex||this._zindex;this.Init()},_defaultName:"Layer"};
a._name=a.GetDefaultName()+ArmContext.GetNewUnicalNumber();a._containerElement=null;a._canvasElement=null;a._ctx=null;a._width=500;a._height=500;a._left=0;a._top=0;a._onMouseDown=[];a._onMouseUp=[];a._onMouseMove=[];a._primitives=new ArmContext.Primitives;a.Set(b);return a}})(window);(function(window){var ArmGraph=function(){var me={};me._lastUnicalNumber=0;me.GetNewUnicalNumber=function(){this._lastUnicalNumber+=1;return this._lastUnicalNumber};return me};window.ArmGraph=ArmGraph()})(window);
(function(window){var EventStack=function(){var me={};me.Push=function(reg){try{this._stack.push(reg);return true}catch(e){return false}};me.Pop=function(){var event=this._stack.shift();if(event!=undefined)return event;else return false};me._stack=[];return me};window.ArmGraph.EventStack=EventStack})(window);
(function(window){var Root=function(O){var me={};me.__begin=function(){for(var i in this._childs)this._childs[i].__begin()};me.__update=function(){for(var i in this._childs)this._childs[i].__update()};me.__draw=function(){for(var i in this._childs)this._childs[i].__draw()};me.__clear=function(){for(var i=0;i<this._childs.length;i++)this._childs[i].__clear()};me.__onKeyDown=function(e){for(var i in this._childs)if(this._childs[i]._onKeyDown)this._childs[i]._onKeyDown(e)};me.__onKeyPress=function(e){for(var i in this._childs)this._childs[i].__onKeyPress(e)};
me.__onKeyUp=function(e){for(var i in this._childs)this._childs[i].__onKeyUp(e)};me.__onMouseDown=function(e){for(var i in this._childs)this._childs[i].__onMouseDown(e)};me.__onMouseUp=function(e){for(var i in this._childs)this._childs[i].__onMouseUp(e)};me.__onMouseMove=function(e){for(var i in this._childs)this._childs[i].__onMouseMove(e)};me.AddChild=function(O){gizmo.Filter(O,"Object");this._childs.push(O)};me.RemoveChild=function(O){gizmo.Filter(O,"Object");var index=0;if((index=this._childs.indexOf(O))!=
-1)delete this._childs[index]};me.Start=function(){this.__begin();this.Start=function(){if(this._isRuning){this.Stop();this.NotListenKeybordEvents()}this.ListenKeybordEvents();var step=function(O){return function(){O.__processEvents();O.__update();O.__clear();O.__draw()}}(this);this._onEachFrame(step);this._isRuning=true;return this};this.Start();return this};me.Stop=function(){if(this._request){this._cancelAnimationFrame.call(window,this._request);this._isRuning=false}};me.SetEachFrame=function(){var self=
this;var _onEachFrame;if(this._fps>0){var fps=this._fps;_onEachFrame=function(cb){this._request=setInterval(cb,1E3/fps)};this._cancelAnimationFrame=window.clearInterval}else{if(window.webkitRequestAnimationFrame)_onEachFrame=function(cb){var _cb=function(){cb();self._request=webkitRequestAnimationFrame(_cb)};_cb()};else if(window.mozRequestAnimationFrame)_onEachFrame=function(cb){var _cb=function(){cb();self._request=mozRequestAnimationFrame(_cb)};_cb()};else if(window.requestAnimationFrame)_onEachFrame=
function(cb){var _cb=function(){cb();self._request=requestAnimationFrame(_cb)};_cb()};else if(window.msRequestAnimationFrame)_onEachFrame=function(cb){var _cb=function(){cb();self._request=msRequestAnimationFrame(_cb)};_cb()};this._cancelAnimationFrame=window.cancelAnimationFrame||window.mozCancelAnimationFrame}this._onEachFrame=_onEachFrame};me.ListenKeybordEvents=function(){var self=this;window.onkeydown=function(e){self.SendEvent({name:"onKeyDown",type:"keyboard",e:e})};window.onkeypress=function(e){self.SendEvent({name:"onKeyPress",
type:"keyboard",e:e})};window.onkeyup=function(e){self.SendEvent({name:"onKeyUp",type:"keyboard",e:e})}};me.NotListenKeybordEvents=function(){var self=this;window.onkeydown=null;window.onkeypress=null;window.onkeyup=null};me.SendEvent=function(event){this._eventStack.Push(event)};me.__processEvents=function(){var event;while(event=this._eventStack.Pop())switch(event.name){case "onKeyDown":this.__onKeyDown(event.e);break;case "onKeyUp":this.__onKeyUp(event.e);break;case "onKeyPress":this.__onKeyPress(event.e);
break;case "onMouseDown":this.__onMouseDown(event);break;case "onMouseUp":this.__onMouseUp(event);break;case "onMouseMove":this.__onMouseMove(event);break}};me.Set=function(O){for(var name in O)switch(name){case "layer":switch(gizmo.type(O[name])){case "Array":for(var layer in O[name]){this._layers.push(O[name][layer]);O[name][layer].SetLisener("onMouseMove",this.__onMouseMove);O[name][layer].SetLisener("onMouseDown",this.__onMouseDown);O[name][layer].SetLisener("onMouseUp",this.__onMouseUp)}break;
case "Object":this._layers.push(O[name]);var self=this;O[name].SetLisener("onMouseMove",function(e){self.__onMouseMove(e)});O[name].SetLisener("onMouseDown",function(e){self.__onMouseDown(e)});O[name].SetLisener("onMouseUp",function(e){self.__onMouseUp(e)});break}break;case "fps":this._fps=O[name];break}if(this._isRuning){this.Stop();this.SetEachFrame();this.Start()}else this.SetEachFrame()};me._childs=[];me._fps=0;me._onEachFrame=null;me._cancelAnimationFrame=null;me._request=null;me._isRuning=false;
me._layers=[];me._eventStack=new ArmGraph.EventStack,me.Set(O||{});return me};window.ArmGraph.Root=Root})(window);
(function(window){var ArmObject=function(O){var me={};me.GetDefaultName=function(){return this._defaultName};me.__begin=function(){if(this._begin)this._begin();for(var i in this._childs)this._childs[i].__begin();if(this._afterBegin)this._afterBegin()};me.__update=function(){if(this._update)this._update();for(var i in this._childs)this._childs[i].__update();if(this._afterUpdate)this._afterUpdate()};me.__draw=function(){if(this._draw)this._draw();for(var i in this._childs)this._childs[i].__draw();if(this._afterDraw)this._afterDraw()};
me.__clear=function(){if(this._clear)this._clear();for(var i=this._childs.length-1;i>=0;i--)this._childs[i].__clear();if(this._afterClear)this._afterClear()};me.__onKeyDown=function(e){if(this._onKeyDown)this._onKeyDown(e);for(var i in this._childs)this._childs[i].__onKeyDown(e)};me.__onKeyPress=function(e){if(this._onKeyPress)this._onKeyPress(e);for(var i in this._childs)this._childs[i].__onKeyPress(e)};me.__onKeyUp=function(e){if(this._onKeyUp)this._onKeyUp(e);for(var i in this._childs)this._childs[i].__onKeyUp(e)};
me.__onMouseDown=function(e){if(this._onMouseDown)this._onMouseDown(e);for(var i in this._childs)this._childs[i].__onMouseDown(e)};me.__onMouseUp=function(e){if(this._onMouseUp)this._onMouseUp(e);for(var i in this._childs)this._childs[i].__onMouseUp(e)};me.__onMouseMove=function(e){if(this._onMouseMove)this._onMouseMove(e);for(var i in this._childs)this._childs[i].__onMouseMove(e)};me.AddChild=function(O){gizmo.Filter(O,"Object");this._childs.push(O)};me.RemoveChild=function(O){gizmo.Filter(O,"Object");
var index=0;if((index=this._childs.indexOf(O))!=-1)delete this._childs[index]};me.SetFunc=function(name,func){gizmo.Filter(name,"String");gizmo.Filter(func,"Function");if(name&&func)this["_"+name]=func;return this};me.GetFunc=function(name){gizmo.Filter(name,"String");if(this["_"+name])return this["_"+name]};me.SetProp=function(name,value){gizmo.Filter(name,"String");if(name&&value)this["_"+name]=value;return this};me.GetProp=function(name){gizmo.Filter(name,"String");if(this["_"+name])return this["_"+
name]};me.HaveOwner=function(){if(this._owner)return true;else return false};me.SetName=function(name){gizmo.Filter(name,"String");this._name=name};me.SetOwner=function(object){gizmo.Filter(object,"object");this._owner=object};me.GetOwner=function(){return this._owner};me.Set=function(O){if(!O)O={};this._owner=O.owner||this._owner;this._name=O.name||this._name;if(this._owner)this._owner.AddChild(this)};me._defaultName="ArmObject";me._name=me.GetDefaultName()+ArmGraph.GetNewUnicalNumber();me._owner=
null;me._childs=[];me.Set(O);return me};window.ArmGraph.ArmObject=ArmObject})(window);
